# Generated by Django 3.2.5 on 2022-11-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('preco', models.CharField(max_length=9)),
                ('descricao', models.CharField(max_length=11)),
                ('categoria', models.CharField(max_length=40)),
            ],
        ),
    ]
